# Generated by Django 5.2.6 on 2026-01-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_fullname_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_user',
        ),
    ]
