# Generated by Django 5.2.6 on 2026-01-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_admin_user_is_user'),
    ]

    operations = [
    ]
